services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - shared_mongo:/data/db # bind the mongodata volume to the /data/db directory in the container
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # execute the init-mongo.js script when the container starts
    ports:
      - 9999:27017 # expose the port 27017 of the container to the host

  api:
    container_name: detection-api
    image: teamcvaiacademy/vds:demo
    restart: always
    ports:
      - 8080:8080
      - 8081:8081

volumes:
  shared_mongo: # declare the mongodata volume
    name: shared_mongo
