services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - shared_mongo:/data/db # bind the mongodata volume to the /data/db directory in the container
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js # execute the init-mongo.js script when the container starts
    ports:
      - 9999:27017 # expose the port 27017 of the container to the host
  vds-core:
    container_name: vds-core
    image: teamcvaiacademy/vds:latest
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "7070:7070"
      - "7071:7071"

volumes:
  shared_mongo: # declare the mongodata volume
